/**
 * Share-URL codec: version dispatch, v1.5 fixture pinning, v2 round-trip
 * tolerance, and typed decode failures.
 *
 * The v1.5 fixtures in __fixtures__/ are frozen payloads generated by the
 * pre-v2 codec (see __fixtures__/README.md); they prove that links shared
 * by v1.5 builds keep decoding through the retained v1.5 path.
 */

import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

import { init } from "@/core/dh";
import {
  CorruptFieldError,
  decodePresetFileText,
  documentToV1,
  InvalidFileError,
  migrateV1ToDocument,
  UnknownKitError,
  UnsupportedVersionError,
  type PresetDocument,
} from "@/features/preset/document";
import type { PresetFileV1 } from "@/features/preset/types/preset";
import { buildDenseSharePreset } from "./__fixtures__/dense-preset";
import { encodeCompactDocument, type CompactPresetV2 } from "./compact-v2";
import { compress } from "./compress";
import { shareableDocumentToUrl, urlToDocument } from "./index";

// --- Helpers ----------------------------------------------------------------

function shareFixture(name: string): string {
  return readFileSync(
    new URL(`./__fixtures__/${name}`, import.meta.url),
    "utf-8",
  ).trim();
}

function documentFixture(name: string): string {
  return readFileSync(
    new URL(`../../document/__fixtures__/${name}`, import.meta.url),
    "utf-8",
  );
}

/** Everything but the decode-minted timestamps. */
function stripTimestamps(document: PresetDocument) {
  const { createdAt: _c, updatedAt: _u, ...meta } = document.meta;
  return { ...document, meta };
}

/**
 * Half the 0.1 knob display step: the codec's quantization contract
 * (see the precision table in compact-v2.ts).
 */
const KNOB_TOLERANCE = 0.05;

const NUMERIC_PARAM_KEYS = [
  "decay",
  "filter",
  "volume",
  "pan",
  "tune",
] as const;

/**
 * Assert that two documents are knob-equivalent: their documentToV1 knob
 * values differ by less than KNOB_TOLERANCE, with pattern, chain, kit, and
 * identity data exact (velocities within the shared 0-100 quantization).
 */
function expectKnobEquivalent(
  actual: PresetDocument,
  expected: PresetDocument,
): void {
  // Exact fields first.
  expect(actual.kit.id).toBe(expected.kit.id);
  expect(actual.meta.id).toBe(expected.meta.id);
  expect(actual.meta.name).toBe(expected.meta.name);
  expect(actual.playback).toEqual(expected.playback);
  expect(actual.transport.bpm).toBe(expected.transport.bpm);
  expect(actual.master.compRatio).toBe(expected.master.compRatio);

  // Pattern: exact except velocities, which share the 0-100 quantization.
  actual.pattern.voices.forEach((voice, v) => {
    const expectedVoice = expected.pattern.voices[v];
    expect(voice.instrumentIndex).toBe(expectedVoice.instrumentIndex);
    voice.variations.forEach((seq, q) => {
      const expectedSeq = expectedVoice.variations[q];
      expect(seq.triggers).toEqual(expectedSeq.triggers);
      expect(seq.ratchets).toEqual(expectedSeq.ratchets);
      expect(seq.flams).toEqual(expectedSeq.flams);
      expect(seq.timingNudge).toBe(expectedSeq.timingNudge);
      seq.velocities.forEach((velocity, s) => {
        expect(
          Math.abs(velocity - expectedSeq.velocities[s]),
        ).toBeLessThanOrEqual(0.005);
      });
    });
  });
  expect(actual.pattern.variationMetadata).toEqual(
    expected.pattern.variationMetadata,
  );

  // Knob-space comparison through the live inverse mappings.
  const actualV1 = documentToV1(actual);
  const expectedV1 = documentToV1(expected);

  actualV1.kit.instruments.forEach((instrument, i) => {
    const expectedParams = expectedV1.kit.instruments[i].params;
    for (const key of NUMERIC_PARAM_KEYS) {
      expect(
        Math.abs(instrument.params[key] - expectedParams[key]),
        `channel ${i} ${key}`,
      ).toBeLessThan(KNOB_TOLERANCE);
    }
    expect(instrument.params.solo).toBe(expectedParams.solo);
    expect(instrument.params.mute).toBe(expectedParams.mute);
  });

  const masterKeys = Object.keys(
    expectedV1.masterChain,
  ) as (keyof PresetFileV1["masterChain"])[];
  for (const key of masterKeys) {
    const actualValue = actualV1.masterChain[key];
    const expectedValue = expectedV1.masterChain[key];
    if (typeof expectedValue !== "number") continue;
    expect(
      Math.abs((actualValue as number) - expectedValue),
      `master ${key}`,
    ).toBeLessThan(KNOB_TOLERANCE);
  }

  expect(
    Math.abs(actualV1.transport.swing - expectedV1.transport.swing),
    "swing knob",
  ).toBeLessThan(KNOB_TOLERANCE);
}

/** A schema-valid dense synthetic document exercising v2-only spellings. */
function buildDenseSyntheticDocument(): PresetDocument {
  const document = migrateV1ToDocument(buildDenseSharePreset());
  return {
    ...document,
    channels: document.channels.map((channel, i) => ({
      ...channel,
      // Off-grid domain values that must round-trip within knob tolerance.
      decaySeconds: 0.005 + i * 0.61234567891,
      filter: 3.7 + i * 12.345,
      volumeDb: i === 0 ? null : -45.123456789 + i * 6.2,
      pan: -1 + i * 0.2857142857,
      tuneSemitones: -7 + i * 1.9876543,
      solo: i % 3 === 0,
      mute: i % 2 === 1,
    })) as PresetDocument["channels"],
    playback: {
      // Max chain: 8 steps, max repeats.
      chain: {
        steps: Array.from({ length: 8 }, (_, i) => ({
          variation: (i % 4) as 0 | 1 | 2 | 3,
          repeats: 8 - (i % 3),
        })),
      },
      chainEnabled: true,
    },
    transport: { bpm: 173.5, swing: 0.31415926 },
    master: {
      filter: 61.803398875,
      saturation: 0.123456789,
      phaser: 0.987654321,
      reverb: 0.5555555,
      compThresholdDb: -13.579246,
      compRatio: 7,
      compAttackSeconds: 0.001 + 0.012345678,
      compMix: 0.246813579,
      masterVolumeDb: null,
    },
  };
}

/** Build a compressed ?p= payload from an arbitrary JSON value. */
function payloadOf(value: unknown): string {
  return compress(JSON.stringify(value));
}

function validV2Payload(): CompactPresetV2 {
  return encodeCompactDocument(buildDenseSyntheticDocument());
}

// --- v1.5 fixture pinning -----------------------------------------------------

describe("v1.5 share fixtures keep decoding", () => {
  it("decodes the frozen init link to the migrated init document", () => {
    const document = urlToDocument(shareFixture("share-v1_5-init.txt"));

    expect(document.kit.id).toBe("kit-0");
    expect(document.meta.name).toBe("init");
    expect(document.transport.bpm).toBe(100);
    expect(document.transport.swing).toBe(0);

    const expected = migrateV1ToDocument(init());
    expect(stripTimestamps(document)).toEqual(stripTimestamps(expected));
  });

  it("decodes the frozen dense link to the pinned dense document", () => {
    const document = urlToDocument(shareFixture("share-v1_5-dense.txt"));

    // Spot pins independent of the migration machinery.
    expect(document.kit.id).toBe("kit-3");
    expect(document.meta.id).toBe("6f9b1c22-0d4e-4b9a-9c33-7d1a2e5b8f40");
    expect(document.meta.name).toBe("Dense Fixture");
    expect(document.transport.bpm).toBe(137);
    // v1.5 swing knob 64 through the v1.5 interpretation: 0.64 * 0.375.
    expect(document.transport.swing).toBeCloseTo(0.24, 10);
    expect(document.channels[0].volumeDb).toBeNull();
    expect(document.master.masterVolumeDb).toBeNull();
    expect(document.master.compRatio).toBe(6);
    expect(document.playback.chainEnabled).toBe(true);
    expect(document.playback.chain.steps).toEqual([
      { variation: 0, repeats: 2 },
      { variation: 1, repeats: 1 },
      { variation: 3, repeats: 3 },
    ]);

    const expected = migrateV1ToDocument(buildDenseSharePreset());
    expect(stripTimestamps(document)).toEqual(stripTimestamps(expected));
  });
});

// --- v2 round-trips -----------------------------------------------------------

describe("v2 codec round-trips within knob resolution", () => {
  const eraFixtures = [
    "v1-current.json",
    "v1-legacy-cycle.json",
    "v1-legacy-master.json",
    "v1-legacy-params.json",
    "v1-legacy-pattern-array.json",
  ];

  for (const fixture of eraFixtures) {
    it(`round-trips the migrated document of ${fixture}`, () => {
      const original = decodePresetFileText(documentFixture(fixture));
      const decoded = urlToDocument(shareableDocumentToUrl(original));
      expectKnobEquivalent(decoded, original);
    });
  }

  it("round-trips the migrated v1.5 share fixtures", () => {
    for (const fixture of ["share-v1_5-init.txt", "share-v1_5-dense.txt"]) {
      const original = urlToDocument(shareFixture(fixture));
      const decoded = urlToDocument(shareableDocumentToUrl(original));
      expectKnobEquivalent(decoded, original);
    }
  });

  it("round-trips a dense synthetic document (null volumes, max chain)", () => {
    const original = buildDenseSyntheticDocument();
    const decoded = urlToDocument(shareableDocumentToUrl(original));

    expectKnobEquivalent(decoded, original);
    expect(decoded.channels[0].volumeDb).toBeNull();
    expect(decoded.master.masterVolumeDb).toBeNull();
    expect(decoded.playback.chain.steps).toHaveLength(8);
  });

  it("encodes the stable kit id, not a positional code", () => {
    const compact = validV2Payload();
    expect(compact.v).toBe(2);
    expect(compact.k).toBe("kit-3");
  });
});

// --- Typed decode failures ----------------------------------------------------

describe("urlToDocument typed failures", () => {
  it("refuses a versionless (pre-#269) payload with UnsupportedVersionError", () => {
    // A hand-built truncated legacy payload: valid compact structure, no v.
    const legacy = {
      id: "legacy",
      k: "0",
      n: "Old Link",
      ip: [{}, {}, {}, {}, {}, {}, {}, {}],
      pt: [],
    };
    expect(() => urlToDocument(payloadOf(legacy))).toThrow(
      UnsupportedVersionError,
    );
  });

  it("refuses unknown future versions with UnsupportedVersionError", () => {
    expect(() =>
      urlToDocument(payloadOf({ ...validV2Payload(), v: 3 })),
    ).toThrow(UnsupportedVersionError);
  });

  it("rejects garbage payloads with InvalidFileError", () => {
    expect(() => urlToDocument("!!!not-a-payload!!!")).toThrow(
      InvalidFileError,
    );
  });

  it("rejects a short ip array with CorruptFieldError at ip", () => {
    const payload = { ...validV2Payload(), ip: [{}, {}] };
    expect(() => urlToDocument(payloadOf(payload))).toThrow(CorruptFieldError);
    try {
      urlToDocument(payloadOf(payload));
    } catch (error) {
      expect((error as CorruptFieldError).path).toBe("ip");
    }
  });

  it("rejects a short pt array with CorruptFieldError at pt", () => {
    const payload = {
      ...validV2Payload(),
      pt: validV2Payload().pt.slice(0, 3),
    };
    try {
      urlToDocument(payloadOf(payload));
      expect.unreachable("should have thrown");
    } catch (error) {
      expect(error).toBeInstanceOf(CorruptFieldError);
      expect((error as CorruptFieldError).path).toBe("pt");
    }
  });

  it("rejects a corrupt trigger bitmap with a step-level path", () => {
    const payload = validV2Payload();
    payload.pt[2].a.t = "zzzz";
    try {
      urlToDocument(payloadOf(payload));
      expect.unreachable("should have thrown");
    } catch (error) {
      expect(error).toBeInstanceOf(CorruptFieldError);
      expect((error as CorruptFieldError).path).toBe("pt.2.a.t");
    }
  });

  it("rejects an out-of-range velocity step index", () => {
    const payload = validV2Payload();
    payload.pt[0].a.v = { "-1": 50 };
    try {
      urlToDocument(payloadOf(payload));
      expect.unreachable("should have thrown");
    } catch (error) {
      expect(error).toBeInstanceOf(CorruptFieldError);
      expect((error as CorruptFieldError).path).toBe("pt.0.a.v.-1");
    }
  });

  it("rejects a malformed chain string with CorruptFieldError at ch", () => {
    const payload = { ...validV2Payload(), ch: "A2Q9" };
    try {
      urlToDocument(payloadOf(payload));
      expect.unreachable("should have thrown");
    } catch (error) {
      expect(error).toBeInstanceOf(CorruptFieldError);
      expect((error as CorruptFieldError).path).toBe("ch");
    }
  });

  it("rejects an unknown kit id with UnknownKitError", () => {
    const payload = { ...validV2Payload(), k: "kit-99" };
    try {
      urlToDocument(payloadOf(payload));
      expect.unreachable("should have thrown");
    } catch (error) {
      expect(error).toBeInstanceOf(UnknownKitError);
      expect((error as UnknownKitError).kitId).toBe("kit-99");
    }
  });

  it("rejects out-of-range domain values via the schema with a document path", () => {
    const payload = validV2Payload();
    payload.ip[0] = { ...payload.ip[0], v: 99 }; // volumeDb max is 4
    try {
      urlToDocument(payloadOf(payload));
      expect.unreachable("should have thrown");
    } catch (error) {
      expect(error).toBeInstanceOf(CorruptFieldError);
      expect((error as CorruptFieldError).path).toBe("channels.0.volumeDb");
    }
  });
});

// --- Size sanity ----------------------------------------------------------------

describe("encoded size report", () => {
  it("logs v1.5 vs v2 payload lengths (informational, no assertion)", () => {
    const initV15 = shareFixture("share-v1_5-init.txt");
    const denseV15 = shareFixture("share-v1_5-dense.txt");
    const initV2 = shareableDocumentToUrl(migrateV1ToDocument(init()));
    const denseV2 = shareableDocumentToUrl(
      migrateV1ToDocument(buildDenseSharePreset()),
    );

    console.log(
      `share payload lengths (chars): init v1.5=${initV15.length} v2=${initV2.length}; ` +
        `dense v1.5=${denseV15.length} v2=${denseV2.length}`,
    );
  });
});
