import { Preset } from "@/types/types";
import * as kits from "@/lib/kits";

export const polaroid_bounce = (): Preset => ({
  name: "polaroid_bounce",
  _kit: kits.funk(),
  _sequences: [
    [
      [
        [
          true,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0.4868624420401855],
      ],
      [
        [
          true,
          false,
          true,
          false,
          false,
          true,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
        ],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0.4868624420401855],
      ],
    ],
    [
      [
        [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      ],
      [
        [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          true,
          false,
          false,
          false,
          false,
          false,
        ],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      ],
    ],
    [
      [
        [
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
        ],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      ],
      [
        [
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
        ],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      ],
    ],
    [
      [
        [
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
        ],
        [
          1, 1, 1, 1, 0.5440494590417311, 1, 1, 1, 1, 1, 1, 1,
          0.5687789799072643, 1, 1, 1,
        ],
      ],
      [
        [
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          true,
          true,
        ],
        [
          1, 1, 1, 1, 0.5069551777434312, 1, 1, 1, 1, 1, 1, 1,
          0.5440494590417311, 1, 0.5347758887171561, 0.4992272024729521,
        ],
      ],
    ],
    [
      [
        [
          true,
          false,
          false,
          true,
          true,
          false,
          false,
          true,
          true,
          false,
          false,
          true,
          true,
          true,
          false,
          true,
        ],
        [
          1, 1, 1, 0.24574961360123648, 1, 1, 1, 0.23956723338485317, 1, 1, 1,
          0.3323029366306028, 1, 0.34775888717156106, 1, 0.1901081916537867,
        ],
      ],
      [
        [
          true,
          false,
          false,
          true,
          true,
          false,
          false,
          false,
          true,
          false,
          false,
          true,
          true,
          false,
          true,
          true,
        ],
        [
          1, 1, 1, 0.24574961360123648, 1, 1, 1, 1, 1, 1, 1,
          0.14683153013910355, 1, 1, 0.32457496136012365, 0.20247295208655333,
        ],
      ],
    ],
    [
      [
        [
          false,
          false,
          true,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          true,
          false,
        ],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      ],
      [
        [
          false,
          false,
          true,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          true,
          false,
        ],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      ],
    ],
    [
      [
        [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      ],
      [
        [
          false,
          true,
          false,
          false,
          true,
          false,
          false,
          true,
          true,
          true,
          false,
          false,
          false,
          false,
          true,
          true,
        ],
        [
          1, 1, 1, 1, 1, 1, 1, 0.6352395672333848, 0.4265842349304482,
          0.2302936630602782, 1, 1, 1, 1, 1, 1,
        ],
      ],
    ],
    [
      [
        [
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      ],
      [
        [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      ],
    ],
  ],
  _variation: 0,
  _chain: 2,
  _bpm: 107,
  _swing: 0,
  _lowPass: 100,
  _hiPass: 0,
  _phaser: 24,
  _reverb: 42,
  _compThreshold: 55,
  _compRatio: 40,
  _masterVolume: 92,
});
