import { Preset } from "@/types/types";
import * as kits from "@/lib/kits";

export const super_dream_haus = (): Preset => ({
  name: "super_dream_haus",
  _kit: kits.jungle(),
  _sequences: [
    [
      [
        [
          true,
          false,
          true,
          false,
          false,
          false,
          true,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
        ],
        [
          1, 1, 1, 1, 1, 1, 1, 1, 0.2596599690880989, 1, 1, 1, 1, 1, 1,
          0.3941267387944359,
        ],
      ],
      [
        [
          true,
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
        ],
        [
          1, 1, 1, 1, 1, 1, 1, 1, 0.2596599690880989, 1, 1, 1, 1, 1, 1,
          0.3941267387944359,
        ],
      ],
    ],
    [
      [
        [
          true,
          false,
          true,
          false,
          false,
          false,
          true,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      ],
      [
        [
          true,
          false,
          true,
          false,
          false,
          false,
          true,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      ],
    ],
    [
      [
        [
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          true,
          false,
          false,
        ],
        [
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0.5378670788253478,
          0.4652241112828439, 0.6769706336939721, 1,
        ],
      ],
      [
        [
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          true,
          true,
          true,
          true,
        ],
        [
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0.5378670788253478,
          0.4652241112828439, 0.6769706336939721, 1,
        ],
      ],
    ],
    [
      [
        [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          true,
        ],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      ],
      [
        [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          true,
        ],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      ],
    ],
    [
      [
        [
          true,
          false,
          true,
          false,
          true,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          true,
          true,
          true,
          true,
        ],
        [
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0.5873261205564142,
          0.26738794435857804, 0.47913446676970634, 0.2828438948995363,
        ],
      ],
      [
        [
          true,
          false,
          true,
          false,
          true,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
        ],
        [
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0.5873261205564142,
          0.26738794435857804, 0.47913446676970634, 0.2828438948995363,
        ],
      ],
    ],
    [
      [
        [
          true,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
        [
          0.321483771251932, 1, 0.29984544049459044, 1, 1, 1, 1, 1,
          0.3091190108191654, 1, 1, 1, 1, 1, 1, 1,
        ],
      ],
      [
        [
          true,
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
        ],
        [
          0.321483771251932, 1, 0.29984544049459044, 1, 1, 1, 1, 1,
          0.3091190108191654, 1, 1, 1, 1, 1, 1, 1,
        ],
      ],
    ],
    [
      [
        [
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
        ],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      ],
      [
        [
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          true,
          false,
          true,
          false,
        ],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      ],
    ],
    [
      [
        [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
        [0.35857805255023184, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      ],
      [
        [
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
        [0.35857805255023184, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      ],
    ],
  ],
  _variation: 0,
  _chain: 3,
  _bpm: 160,
  _swing: 0,
  _lowPass: 73,
  _hiPass: 7,
  _phaser: 21,
  _reverb: 56,
  _compThreshold: 51,
  _compRatio: 52,
  _masterVolume: 92,
});
