import * as kits from "@/lib/drumhausKits";
import { sequencesToPattern } from "@/lib/pattern/migrate";
import type { Preset } from "@/types/preset";

export const polaroid_bounce = (): Preset => ({
  name: "polaroid_bounce",
  kit: kits.funk(),
  pattern: sequencesToPattern([
    [
      [
        [
          true,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0.4868624420401855],
      ],
      [
        [
          true,
          false,
          true,
          false,
          false,
          true,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
        ],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0.4868624420401855],
      ],
    ],
    [
      [
        [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      ],
      [
        [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          true,
          false,
          false,
          false,
          false,
          false,
        ],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      ],
    ],
    [
      [
        [
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
        ],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      ],
      [
        [
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
        ],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      ],
    ],
    [
      [
        [
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
        ],
        [
          1, 1, 1, 1, 0.5440494590417311, 1, 1, 1, 1, 1, 1, 1,
          0.5687789799072643, 1, 1, 1,
        ],
      ],
      [
        [
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          true,
          true,
        ],
        [
          1, 1, 1, 1, 0.5069551777434312, 1, 1, 1, 1, 1, 1, 1,
          0.5440494590417311, 1, 0.5347758887171561, 0.4992272024729521,
        ],
      ],
    ],
    [
      [
        [
          true,
          false,
          false,
          true,
          true,
          false,
          false,
          true,
          true,
          false,
          false,
          true,
          true,
          true,
          false,
          true,
        ],
        [
          1, 1, 1, 0.24574961360123648, 1, 1, 1, 0.23956723338485317, 1, 1, 1,
          0.3323029366306028, 1, 0.34775888717156106, 1, 0.1901081916537867,
        ],
      ],
      [
        [
          true,
          false,
          false,
          true,
          true,
          false,
          false,
          false,
          true,
          false,
          false,
          true,
          true,
          false,
          true,
          true,
        ],
        [
          1, 1, 1, 0.24574961360123648, 1, 1, 1, 1, 1, 1, 1,
          0.14683153013910355, 1, 1, 0.32457496136012365, 0.20247295208655333,
        ],
      ],
    ],
    [
      [
        [
          false,
          false,
          true,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          true,
          false,
        ],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      ],
      [
        [
          false,
          false,
          true,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          true,
          false,
        ],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      ],
    ],
    [
      [
        [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      ],
      [
        [
          false,
          true,
          false,
          false,
          true,
          false,
          false,
          true,
          true,
          true,
          false,
          false,
          false,
          false,
          true,
          true,
        ],
        [
          1, 1, 1, 1, 1, 1, 1, 0.6352395672333848, 0.4265842349304482,
          0.2302936630602782, 1, 1, 1, 1, 1, 1,
        ],
      ],
    ],
    [
      [
        [
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      ],
      [
        [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      ],
    ],
  ]),
  variationCycle: "AB",
  bpm: 107,
  swing: 0,
  masterChain: {
    lowPass: 100,
    hiPass: 0,
    phaser: 24,
    reverb: 42,
    compThreshold: 55,
    compRatio: 40,
    masterVolume: 92,
  },
});
