import * as kits from "@/lib/drumhausKits";
import { sequencesToPattern } from "@/lib/pattern/migrate";
import type { Preset } from "@/lib/preset/types";

export const slime_time = (): Preset => ({
  name: "slime_time",
  kit: kits.trap(),
  pattern: sequencesToPattern([
    [
      [
        [
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          true,
          false,
        ],
        [
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0.7047913446676971, 1,
          0.7202472952086554, 1,
        ],
      ],
      [
        [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
        ],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0.44976816074188564],
      ],
    ],
    [
      [
        [
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      ],
      [
        [
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
        ],
        [
          1, 1, 1, 1, 0.5193199381761978, 1, 1, 1, 1, 1, 0.5533230293663061, 1,
          1, 1, 1, 1,
        ],
      ],
    ],
    [
      [
        [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      ],
      [
        [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      ],
    ],
    [
      [
        [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      ],
      [
        [
          false,
          false,
          true,
          true,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
        [
          1, 1, 0.8006182380216383, 0.3075734157650695, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1,
        ],
      ],
    ],
    [
      [
        [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      ],
      [
        [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      ],
    ],
    [
      [
        [
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
        ],
        [
          1, 1, 0.42967542503863987, 1, 1, 1, 1, 1, 1, 1, 0.42967542503863987,
          1, 1, 1, 1, 1,
        ],
      ],
      [
        [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      ],
    ],
    [
      [
        [
          false,
          false,
          false,
          false,
          true,
          false,
          true,
          false,
          false,
          false,
          true,
          false,
          true,
          false,
          false,
          false,
        ],
        [
          1, 1, 1, 1, 1, 1, 0.5224111282843895, 1, 1, 1, 1, 1,
          0.482225656877898, 1, 0.3369397217928903, 0.23956723338485317,
        ],
      ],
      [
        [
          false,
          false,
          false,
          false,
          true,
          false,
          true,
          false,
          false,
          false,
          true,
          false,
          true,
          false,
          true,
          true,
        ],
        [
          1, 1, 1, 1, 1, 1, 0.5224111282843895, 1, 1, 1, 1, 1,
          0.482225656877898, 1, 0.3369397217928903, 0.23956723338485317,
        ],
      ],
    ],
    [
      [
        [
          false,
          true,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
        [
          1, 0.26738794435857804, 1, 1, 1, 1, 0.2874806800618238, 1, 1, 1, 1, 1,
          1, 1, 1, 1,
        ],
      ],
      [
        [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          true,
          true,
          true,
        ],
        [
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0.7047913446676971,
          0.3972179289026275, 0.3987635239567233, 0.3261205564142195,
        ],
      ],
    ],
  ]),
  variationCycle: "AB",
  bpm: 124,
  swing: 38,
  masterChain: {
    lowPass: 100,
    hiPass: 0,
    phaser: 0,
    reverb: 27,
    compThreshold: 24,
    compRatio: 55,
    masterVolume: 92,
  },
});
