import * as kits from "@/lib/drumhausKits";
import { sequencesToPattern } from "@/lib/pattern/migrate";
import type { Preset } from "@/lib/preset/types";

export const super_dream_haus = (): Preset => ({
  name: "super_dream_haus",
  kit: kits.jungle(),
  pattern: sequencesToPattern([
    [
      [
        [
          true,
          false,
          true,
          false,
          false,
          false,
          true,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
        ],
        [
          1, 1, 1, 1, 1, 1, 1, 1, 0.2596599690880989, 1, 1, 1, 1, 1, 1,
          0.3941267387944359,
        ],
      ],
      [
        [
          true,
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
        ],
        [
          1, 1, 1, 1, 1, 1, 1, 1, 0.2596599690880989, 1, 1, 1, 1, 1, 1,
          0.3941267387944359,
        ],
      ],
    ],
    [
      [
        [
          true,
          false,
          true,
          false,
          false,
          false,
          true,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      ],
      [
        [
          true,
          false,
          true,
          false,
          false,
          false,
          true,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      ],
    ],
    [
      [
        [
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          true,
          false,
          false,
        ],
        [
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0.5378670788253478,
          0.4652241112828439, 0.6769706336939721, 1,
        ],
      ],
      [
        [
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          true,
          true,
          true,
          true,
        ],
        [
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0.5378670788253478,
          0.4652241112828439, 0.6769706336939721, 1,
        ],
      ],
    ],
    [
      [
        [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          true,
        ],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      ],
      [
        [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          true,
        ],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      ],
    ],
    [
      [
        [
          true,
          false,
          true,
          false,
          true,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          true,
          true,
          true,
          true,
        ],
        [
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0.5873261205564142,
          0.26738794435857804, 0.47913446676970634, 0.2828438948995363,
        ],
      ],
      [
        [
          true,
          false,
          true,
          false,
          true,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
        ],
        [
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0.5873261205564142,
          0.26738794435857804, 0.47913446676970634, 0.2828438948995363,
        ],
      ],
    ],
    [
      [
        [
          true,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
        [
          0.321483771251932, 1, 0.29984544049459044, 1, 1, 1, 1, 1,
          0.3091190108191654, 1, 1, 1, 1, 1, 1, 1,
        ],
      ],
      [
        [
          true,
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
        ],
        [
          0.321483771251932, 1, 0.29984544049459044, 1, 1, 1, 1, 1,
          0.3091190108191654, 1, 1, 1, 1, 1, 1, 1,
        ],
      ],
    ],
    [
      [
        [
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
        ],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      ],
      [
        [
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          true,
          false,
          true,
          false,
        ],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      ],
    ],
    [
      [
        [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
        [0.35857805255023184, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      ],
      [
        [
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
        [0.35857805255023184, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      ],
    ],
  ]),
  variationCycle: "AAAB",
  bpm: 160,
  swing: 0,
  masterChain: {
    lowPass: 73,
    hiPass: 7,
    phaser: 21,
    reverb: 56,
    compThreshold: 51,
    compRatio: 52,
    masterVolume: 92,
  },
});
