import type { PresetDocument } from "./document";

/**
 * The migrated document surface (everything except `pattern`) pinned for
 * every era fixture, generated once from migrateV1ToDocument and anchored
 * by the hand-verified spot values in migrate-v1.test.ts.
 *
 * `pattern` is deliberately not pinned here: the migration reuses
 * migratePattern verbatim, and pattern integrity is covered structurally
 * by corpus.test.ts and by the migrate -> toV1 -> migrate round-trip.
 *
 * These are explicit literals, not snapshots, on purpose: updating them
 * after a deliberate migration change means editing the affected fields by
 * hand and justifying the diff in review. There is no bulk-regenerate
 * command, and that is the point.
 */
type GoldenSurface = Omit<PresetDocument, "pattern">;

const GOLDEN_SURFACES: Record<string, GoldenSurface> = {
  "v1-current.json": {
    kind: "drumhaus.preset",
    version: 2.1,
    meta: {
      id: "53b9eebd-6af5-43ed-b43e-eec354dbc4cc",
      name: "init",
      createdAt: "2023-11-20T16:00:00.000Z",
      updatedAt: "2025-12-12T06:06:27.622Z",
    },
    kit: {
      id: "kit-0",
    },
    channels: [
      {
        decaySeconds: 5,
        filter: { side: "highpass", cutoffHz: 0 },
        volumeDb: 0,
        pan: 0,
        tuneSemitones: 0,
        mute: false,
        solo: false,
      },
      {
        decaySeconds: 5,
        filter: { side: "highpass", cutoffHz: 0 },
        volumeDb: 0,
        pan: 0,
        tuneSemitones: 0,
        mute: false,
        solo: false,
      },
      {
        decaySeconds: 5,
        filter: { side: "highpass", cutoffHz: 0 },
        volumeDb: 0,
        pan: 0,
        tuneSemitones: 0,
        mute: false,
        solo: false,
      },
      {
        decaySeconds: 5,
        filter: { side: "highpass", cutoffHz: 0 },
        volumeDb: 0,
        pan: 0,
        tuneSemitones: 0,
        mute: false,
        solo: false,
      },
      {
        decaySeconds: 5,
        filter: { side: "highpass", cutoffHz: 0 },
        volumeDb: 0,
        pan: 0,
        tuneSemitones: 0,
        mute: false,
        solo: false,
      },
      {
        decaySeconds: 5,
        filter: { side: "highpass", cutoffHz: 0 },
        volumeDb: 0,
        pan: 0,
        tuneSemitones: 0,
        mute: false,
        solo: false,
      },
      {
        decaySeconds: 5,
        filter: { side: "highpass", cutoffHz: 0 },
        volumeDb: 0,
        pan: 0,
        tuneSemitones: 0,
        mute: false,
        solo: false,
      },
      {
        decaySeconds: 5,
        filter: { side: "highpass", cutoffHz: 0 },
        volumeDb: 0,
        pan: 0,
        tuneSemitones: 0,
        mute: false,
        solo: false,
      },
    ],
    playback: {
      chain: {
        steps: [
          {
            variation: 0,
            repeats: 1,
          },
        ],
      },
      chainEnabled: false,
    },
    transport: {
      bpm: 100,
      swing: 0,
    },
    master: {
      filter: { side: "highpass", cutoffHz: 0 },
      saturation: 0,
      phaser: 0,
      reverb: 0,
      compThresholdDb: 0,
      compRatio: 5,
      compAttackSeconds: 0.025750000000000002,
      compMix: 0.7,
      masterVolumeDb: 0,
    },
  },
  "v1-legacy-params.json": {
    kind: "drumhaus.preset",
    version: 2.1,
    meta: {
      id: "53b9eebd-6af5-43ed-b43e-eec354dbc4cc",
      name: "init",
      createdAt: "2023-11-20T16:00:00.000Z",
      updatedAt: "2023-11-20T16:00:00.000Z",
    },
    kit: {
      id: "kit-0",
    },
    channels: [
      {
        decaySeconds: 5,
        filter: { side: "highpass", cutoffHz: 0 },
        volumeDb: 0,
        pan: 0,
        tuneSemitones: 0,
        mute: false,
        solo: false,
      },
      {
        decaySeconds: 5,
        filter: { side: "highpass", cutoffHz: 0 },
        volumeDb: 0,
        pan: 0,
        tuneSemitones: 0,
        mute: false,
        solo: false,
      },
      {
        decaySeconds: 5,
        filter: { side: "highpass", cutoffHz: 0 },
        volumeDb: 0,
        pan: 0,
        tuneSemitones: 0,
        mute: false,
        solo: false,
      },
      {
        decaySeconds: 5,
        filter: { side: "highpass", cutoffHz: 0 },
        volumeDb: 0,
        pan: 0,
        tuneSemitones: 0,
        mute: false,
        solo: false,
      },
      {
        decaySeconds: 5,
        filter: { side: "highpass", cutoffHz: 0 },
        volumeDb: 0,
        pan: 0,
        tuneSemitones: 0,
        mute: false,
        solo: false,
      },
      {
        decaySeconds: 5,
        filter: { side: "highpass", cutoffHz: 0 },
        volumeDb: 0,
        pan: 0,
        tuneSemitones: 0,
        mute: false,
        solo: false,
      },
      {
        decaySeconds: 5,
        filter: { side: "highpass", cutoffHz: 0 },
        volumeDb: 0,
        pan: 0,
        tuneSemitones: 0,
        mute: false,
        solo: false,
      },
      {
        decaySeconds: 5,
        filter: { side: "highpass", cutoffHz: 0 },
        volumeDb: 0,
        pan: 0,
        tuneSemitones: 0,
        mute: false,
        solo: false,
      },
    ],
    playback: {
      chain: {
        steps: [
          {
            variation: 0,
            repeats: 1,
          },
        ],
      },
      chainEnabled: false,
    },
    transport: {
      bpm: 100,
      swing: 0,
    },
    master: {
      filter: { side: "highpass", cutoffHz: 0 },
      saturation: 0,
      phaser: 0,
      reverb: 0,
      compThresholdDb: 0,
      compRatio: 4,
      compAttackSeconds: 0.025750000000000002,
      compMix: 0.7,
      masterVolumeDb: 0,
    },
  },
  "v1-legacy-master.json": {
    kind: "drumhaus.preset",
    version: 2.1,
    meta: {
      id: "53b9eebd-6af5-43ed-b43e-eec354dbc4cc",
      name: "init",
      createdAt: "2023-11-20T16:00:00.000Z",
      updatedAt: "2023-11-20T16:00:00.000Z",
    },
    kit: {
      id: "kit-0",
    },
    channels: [
      {
        decaySeconds: 5,
        filter: { side: "highpass", cutoffHz: 0 },
        volumeDb: 0,
        pan: 0,
        tuneSemitones: 0,
        mute: false,
        solo: false,
      },
      {
        decaySeconds: 5,
        filter: { side: "highpass", cutoffHz: 0 },
        volumeDb: 0,
        pan: 0,
        tuneSemitones: 0,
        mute: false,
        solo: false,
      },
      {
        decaySeconds: 5,
        filter: { side: "highpass", cutoffHz: 0 },
        volumeDb: 0,
        pan: 0,
        tuneSemitones: 0,
        mute: false,
        solo: false,
      },
      {
        decaySeconds: 5,
        filter: { side: "highpass", cutoffHz: 0 },
        volumeDb: 0,
        pan: 0,
        tuneSemitones: 0,
        mute: false,
        solo: false,
      },
      {
        decaySeconds: 5,
        filter: { side: "highpass", cutoffHz: 0 },
        volumeDb: 0,
        pan: 0,
        tuneSemitones: 0,
        mute: false,
        solo: false,
      },
      {
        decaySeconds: 5,
        filter: { side: "highpass", cutoffHz: 0 },
        volumeDb: 0,
        pan: 0,
        tuneSemitones: 0,
        mute: false,
        solo: false,
      },
      {
        decaySeconds: 5,
        filter: { side: "highpass", cutoffHz: 0 },
        volumeDb: 0,
        pan: 0,
        tuneSemitones: 0,
        mute: false,
        solo: false,
      },
      {
        decaySeconds: 5,
        filter: { side: "highpass", cutoffHz: 0 },
        volumeDb: 0,
        pan: 0,
        tuneSemitones: 0,
        mute: false,
        solo: false,
      },
    ],
    playback: {
      chain: {
        steps: [
          {
            variation: 0,
            repeats: 1,
          },
        ],
      },
      chainEnabled: false,
    },
    transport: {
      bpm: 100,
      swing: 0,
    },
    master: {
      filter: { side: "highpass", cutoffHz: 0 },
      saturation: 0,
      phaser: 0,
      reverb: 0,
      compThresholdDb: 0,
      compRatio: 4,
      compAttackSeconds: 0.025750000000000002,
      compMix: 0.7,
      masterVolumeDb: 0,
    },
  },
  "v1-legacy-cycle.json": {
    kind: "drumhaus.preset",
    version: 2.1,
    meta: {
      id: "53b9eebd-6af5-43ed-b43e-eec354dbc4cc",
      name: "init",
      createdAt: "2023-11-20T16:00:00.000Z",
      updatedAt: "2025-12-12T06:06:27.622Z",
    },
    kit: {
      id: "kit-0",
    },
    channels: [
      {
        decaySeconds: 5,
        filter: { side: "highpass", cutoffHz: 0 },
        volumeDb: 0,
        pan: 0,
        tuneSemitones: 0,
        mute: false,
        solo: false,
      },
      {
        decaySeconds: 5,
        filter: { side: "highpass", cutoffHz: 0 },
        volumeDb: 0,
        pan: 0,
        tuneSemitones: 0,
        mute: false,
        solo: false,
      },
      {
        decaySeconds: 5,
        filter: { side: "highpass", cutoffHz: 0 },
        volumeDb: 0,
        pan: 0,
        tuneSemitones: 0,
        mute: false,
        solo: false,
      },
      {
        decaySeconds: 5,
        filter: { side: "highpass", cutoffHz: 0 },
        volumeDb: 0,
        pan: 0,
        tuneSemitones: 0,
        mute: false,
        solo: false,
      },
      {
        decaySeconds: 5,
        filter: { side: "highpass", cutoffHz: 0 },
        volumeDb: 0,
        pan: 0,
        tuneSemitones: 0,
        mute: false,
        solo: false,
      },
      {
        decaySeconds: 5,
        filter: { side: "highpass", cutoffHz: 0 },
        volumeDb: 0,
        pan: 0,
        tuneSemitones: 0,
        mute: false,
        solo: false,
      },
      {
        decaySeconds: 5,
        filter: { side: "highpass", cutoffHz: 0 },
        volumeDb: 0,
        pan: 0,
        tuneSemitones: 0,
        mute: false,
        solo: false,
      },
      {
        decaySeconds: 5,
        filter: { side: "highpass", cutoffHz: 0 },
        volumeDb: 0,
        pan: 0,
        tuneSemitones: 0,
        mute: false,
        solo: false,
      },
    ],
    playback: {
      chain: {
        steps: [
          {
            variation: 0,
            repeats: 1,
          },
          {
            variation: 1,
            repeats: 1,
          },
        ],
      },
      chainEnabled: true,
    },
    transport: {
      bpm: 100,
      swing: 0,
    },
    master: {
      filter: { side: "highpass", cutoffHz: 0 },
      saturation: 0,
      phaser: 0,
      reverb: 0,
      compThresholdDb: 0,
      compRatio: 5,
      compAttackSeconds: 0.025750000000000002,
      compMix: 0.7,
      masterVolumeDb: 0,
    },
  },
  "v1-legacy-pattern-array.json": {
    kind: "drumhaus.preset",
    version: 2.1,
    meta: {
      id: "53b9eebd-6af5-43ed-b43e-eec354dbc4cc",
      name: "init",
      createdAt: "2023-11-20T16:00:00.000Z",
      updatedAt: "2023-11-20T16:00:00.000Z",
    },
    kit: {
      id: "kit-0",
    },
    channels: [
      {
        decaySeconds: 5,
        filter: { side: "highpass", cutoffHz: 0 },
        volumeDb: 0,
        pan: 0,
        tuneSemitones: 0,
        mute: false,
        solo: false,
      },
      {
        decaySeconds: 5,
        filter: { side: "highpass", cutoffHz: 0 },
        volumeDb: 0,
        pan: 0,
        tuneSemitones: 0,
        mute: false,
        solo: false,
      },
      {
        decaySeconds: 5,
        filter: { side: "highpass", cutoffHz: 0 },
        volumeDb: 0,
        pan: 0,
        tuneSemitones: 0,
        mute: false,
        solo: false,
      },
      {
        decaySeconds: 5,
        filter: { side: "highpass", cutoffHz: 0 },
        volumeDb: 0,
        pan: 0,
        tuneSemitones: 0,
        mute: false,
        solo: false,
      },
      {
        decaySeconds: 5,
        filter: { side: "highpass", cutoffHz: 0 },
        volumeDb: 0,
        pan: 0,
        tuneSemitones: 0,
        mute: false,
        solo: false,
      },
      {
        decaySeconds: 5,
        filter: { side: "highpass", cutoffHz: 0 },
        volumeDb: 0,
        pan: 0,
        tuneSemitones: 0,
        mute: false,
        solo: false,
      },
      {
        decaySeconds: 5,
        filter: { side: "highpass", cutoffHz: 0 },
        volumeDb: 0,
        pan: 0,
        tuneSemitones: 0,
        mute: false,
        solo: false,
      },
      {
        decaySeconds: 5,
        filter: { side: "highpass", cutoffHz: 0 },
        volumeDb: 0,
        pan: 0,
        tuneSemitones: 0,
        mute: false,
        solo: false,
      },
    ],
    playback: {
      chain: {
        steps: [
          {
            variation: 0,
            repeats: 1,
          },
        ],
      },
      chainEnabled: false,
    },
    transport: {
      bpm: 100,
      swing: 0,
    },
    master: {
      filter: { side: "highpass", cutoffHz: 0 },
      saturation: 0,
      phaser: 0,
      reverb: 0,
      compThresholdDb: 0,
      compRatio: 4,
      compAttackSeconds: 0.025750000000000002,
      compMix: 0.7,
      masterVolumeDb: 0,
    },
  },
};
export { GOLDEN_SURFACES };
export type { GoldenSurface };
