import { init } from "@/core/dh";
import { loadKit } from "@/core/dhkit";
import type { PresetFileV1 } from "@/features/preset/types/preset";

/**
 * Deterministic "dense" knob-space (v1.5) preset used by the share-URL
 * fixture corpus: every channel param, every master param, bpm, swing, a
 * 3-step chain with chainEnabled, and per-step accents/ratchets/flams/
 * nudges/velocities are all off-default, on kit-3.
 *
 * FROZEN: the fixture files in this directory were generated by encoding
 * this preset with the v1.5 share codec. Changing this builder desyncs it
 * from those frozen payloads; regenerate the fixtures if it ever changes
 * deliberately.
 */
function buildDenseSharePreset(): PresetFileV1 {
  // Deep-clone: the tolerant v1 schema passes nested sections through by
  // reference, so init()'s pattern aliases the module-level init.dh JSON.
  // Mutating it un-cloned would leak dense pattern data into every later
  // init() call in the same process.
  const preset = structuredClone(init());

  const kit = loadKit("kit-3");
  if (!kit) throw new Error("kit-3 missing from registry");

  preset.meta = {
    id: "6f9b1c22-0d4e-4b9a-9c33-7d1a2e5b8f40",
    name: "Dense Fixture",
    createdAt: "2026-07-14T00:00:00.000Z",
    updatedAt: "2026-07-14T00:00:00.000Z",
  };

  preset.kit = {
    ...kit,
    instruments: kit.instruments.map((instrument, i) => ({
      ...instrument,
      params: {
        decay: 5 + i * 12,
        filter: 12 + i * 11,
        // Channel 0 at knob 0 pins the null (silence) volume spelling.
        volume: i === 0 ? 0 : 20 + i * 9,
        pan: 4 + i * 13,
        tune: 6 + i * 12,
        solo: i === 2,
        mute: i === 5,
      },
    })),
  };

  const pattern = preset.sequencer.pattern;
  for (let v = 0; v < 8; v++) {
    for (let q = 0; q < 4; q++) {
      const seq = pattern.voices[v].variations[q];
      for (let s = 0; s < 16; s++) {
        seq.triggers[s] = (s + v + q) % 3 === 0;
        seq.velocities[s] = 1;
        seq.ratchets[s] = false;
        seq.flams[s] = false;
      }
      seq.velocities[(v + q) % 16] = 0.35;
      seq.timingNudge = (((v + q) % 5) - 2) as -2 | -1 | 0 | 1 | 2;
      seq.ratchets[(v + 2 * q) % 16] = true;
      seq.flams[(v + 3 * q + 1) % 16] = true;
    }
  }
  for (let q = 0; q < 4; q++) {
    const accent = pattern.variationMetadata[q].accent;
    for (let s = 0; s < 16; s++) {
      accent[s] = s % 4 === q;
    }
  }

  preset.sequencer.chain = {
    steps: [
      { variation: 0, repeats: 2 },
      { variation: 1, repeats: 1 },
      { variation: 3, repeats: 3 },
    ],
  };
  preset.sequencer.chainEnabled = true;

  preset.transport.bpm = 137;
  preset.transport.swing = 64;

  preset.masterChain = {
    filter: 31,
    saturation: 22,
    phaser: 45,
    reverb: 61,
    compThreshold: 40,
    compRatio: 70,
    compAttack: 35,
    compMix: 55,
    // Knob 0 pins the null (silence) master volume spelling.
    masterVolume: 0,
  };

  return preset;
}

export { buildDenseSharePreset };
