const KNOB_VALUE_MAX = 100;
const KNOB_VALUE_MIN = 0;
const KNOB_VALUE_DEFAULT = 50;
const KNOB_OUTER_TICK_COUNT_DEFAULT = 2;
const KNOB_EXPONENTIAL_CURVE_POWER = 2;
const KNOB_SENSITIVITY = 0.7;
const KNOB_SENSITIVITY_MOBILE = 0.6;
const KNOB_ROTATION_RANGE_DEGREES: [number, number] = [-135, 135];

export {
  KNOB_VALUE_MAX,
  KNOB_VALUE_MIN,
  KNOB_VALUE_DEFAULT,
  KNOB_OUTER_TICK_COUNT_DEFAULT,
  KNOB_EXPONENTIAL_CURVE_POWER,
  KNOB_SENSITIVITY,
  KNOB_SENSITIVITY_MOBILE,
  KNOB_ROTATION_RANGE_DEGREES,
};
